# Warning: This workflow is designed to fail. When merging in a PR, pushing an empty commit will bypass checks and allow the PR to be merged.
name: Build Rock

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: "git"
      rock-repo: rockcrafters/git-rock
      rock-repo-commit: main
      rockfile-directory: git
      arch-map: '{"amd64": "ubuntu-latest"}'

  test:
    uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@main
    needs: [build]
    with:
      oci-archive-name: "git"

  # upload:
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Login to GHCR
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}


          