# Warning: This workflow is designed to fail. When merging in a PR, pushing an empty commit will bypass checks and allow the PR to be merged.
name: Build Rock

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */14 * *" # Trigger every 2 weeks at midnight UTC

jobs:
  build:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: "git.rock"
      rock-repo: rockcrafters/git-rock
      rock-repo-commit: main
      rockfile-directory: git
      arch-map: '{"amd64": "ubuntu-latest"}'

  test:
    uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@main
    needs: [build]
    with:
      oci-archive-name: "git.rock"

  upload:
    needs: [test]
    runs-on: ubuntu-latest
    steps:

      - name: Download Rock
        uses: actions/download-artifact@v4
        with:
          name: "git.rock"

      - name: Upload Rock
        env:
          REG_USER: ${{ github.actor }}
          REG_PASW: ${{ secrets.GITHUB_TOKEN }}
          IMG_NAME: "git.rock"
          REP_NAME: "git"
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/workdir -w /workdir \
            "quay.io/skopeo/stable:v1.15.1" \
            copy --dest-creds=${REG_USER}:${REG_PASW} \
            oci-archive:${IMG_NAME} \
            docker://ghcr.io/rockcrafters/${REP_NAME}:latest


